parameters:
- name: syncGitHub
  displayName: Sync with GitHub
  type: boolean
  default: true

trigger:
- none

resources:
  pipelines:
  - pipeline: Release
    source: Release\Bca.Docker
    trigger: 
      branches:
      - master
  repositories:
    - repository: bca-cicd
      type: git
      name: bca-cicd
      ref: refs/tags/1.0

variables:
- template: azuredevops/pipelines/variables/all.yml@bca-cicd


stages: 
- template: azuredevops/pipelines/pipeline-sync-repo.yml@bca-cicd
  parameters:
    syncGitHub: ${{ parameters.syncGitHub }}